# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1506ff961252e8c0cd2e425ba1b1307475944cddc9a38df03e10cb9df2b32a0c98bc99b18c9285a4f9f7e1c640b32fa637b4e64686a411e44ac7c87f6f5bfed

test:
  secret_key_base: 21f1096451050911b49425252eef86b88f21403476056c5ead0205b3fe2bd7b9ec25ac4e4818b512e6fed30eab5e86421f734ca49ca0533e96cfa8c2a48573a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
